export { default as Navbar } from './Navbar'
export { default as About } from './About'
export { default as Team } from './Team'
export { default as Loader } from './Loader'
export { default as Currencies } from './Currencies'
export { default as News } from './News'
export { default as LineChart } from './LineChart'
export { default as Layout } from './Layout'
export { default as Collections } from './Collections'
// export { default as Collection } from './Collection'
export { default as NFTs } from './NFTs'
export { default as NFT } from './NFT'
export { default as SingleNFT } from './SingleNFT'
export { default as Cards } from './Cards'
export { default as Connect } from './Connect'

